name: Run Arbitrum ETL

on:
  schedule:
    - cron: '*/15 * * * *'  # every 15 minutes
  workflow_dispatch:        # allow manual trigger

jobs:
  etl_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        env:
          QUICKNODE_URL: ${{ secrets.QUICKNODE_URL }}
          DB_URI: ${{ secrets.DB_URI }}
        run: |
          python etl_arbitrum.py
